# Config file for automatic testing at travis-ci.org

language: python
  - "2.7"
  - "3.6"
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install --yes libboost-all-dev
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda config --append channels r
  - conda config --append channels defaults
  - conda config --append channels conda-forge
  - conda config --append channels bioconda
  - conda update -q conda
  - conda install conda-build
  - conda install anaconda-client
  - conda install pytest-cov
  - pip install coveralls
install:
  - conda build  .
  - conda install -c kpalin --use-local huddinge_tsne_browser
  - conda info -a
script:
  - conda install -y hypothesis
  - pytest -v --cov=huddinge_tsne_browser tests
after_success:
  - coveralls
