package:
  name: huddinge_tsne_browser
  version: 0.1.0

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - holoviews
  run:
    - python
    - pandas
    - sklearn
    - bokeh
    - numpy
    - holoviews

about:
  home: https://github.com/kpalin/huddinge_tsne_browser
  summary: Tool to browse sequence kmers laid out in 2D with TSNE approximating Huddinge distance
