package:
  name: huddinge_tsne_browser
  version: 0.4.1

source:
  path: ..


extra:
  channels:
    - kpalin

requirements:
  build:
    - python
    - setuptools
  run:
    - psutil
    - python
    - pandas
    - bokeh 
    - scikit-learn
    - holoviews <=1.12.0
#    - holoviews  >=1.9.2
    - jellyfish
    - svgwrite
    - pyhuddinge >=0.2
    - setuptools


test:
  requires:
    - pytest
    - hypothesis
  source_files:
    - tests
  commands:
    - pytest tests/


about:
  home: https://github.com/kpalin/huddinge_tsne_browser
  summary: Tool to browse sequence kmers laid out in 2D with TSNE approximating Huddinge distance
